name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main
    - name: Login to GitHub Container Registry
      run: podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build Test Image
      run: podman build -f Containerfile -t ghcr.io/emblem-66/test:latest
    - name: Push Test Image
      run: podman push ghcr.io/emblem-66/test:latest
